title: Unravel RDF
description: >
  A JavaScript/TypeScript library for exploring RDF graphs 
  and building SPARQL queries without writing SPARQL.
theme: just-the-docs
url: "https://unravel-rdf-5df20c.pages-forge.inrae.fr"

color_scheme: dark
search_enabled: true
nav_enabled: true
heading_anchors: true

aux_links:
  "GitLab":
    - "https://forge.inrae.fr/p2m2/unravel-rdf"
  "GitHub mirror":
    - "https://github.com/p2m2/unravel-rdf"
footer_content: >
  Unravel RDF - INRAE P2M2 -
  The Metabolic Profiling and Metabolomics Platform
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" 
